import {Button} from '@/components/ui/button';
import {Card, CardContent, CardDescription, CardHeader, CardTitle} from '@/components/ui/card';
import {Download, Loader2} from 'lucide-react';

export default function DatevExportPage() {
  return (
    <div className="flex flex-col gap-6">
      <h1 className="text-3xl font-bold font-headline tracking-tight">DATEV CSV Export</h1>
      <Card className="max-w-2xl">
        <CardHeader>
          <CardTitle>Generate Financial Data Export</CardTitle>
          <CardDescription>
            Export your financial transactions in a DATEV-compatible CSV format. This process may take a few moments
            depending on the amount of data.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground mb-4">
            Select the date range for the export and click the button below. The file will be generated by our backend
            and a download will start automatically.
          </p>
          {/* Date range picker could be added here */}
        </CardContent>
        <CardFooter>
          <Button className="bg-accent hover:bg-accent/90">
            <Download className="mr-2 h-4 w-4" />
            Generate & Download DATEV Export
          </Button>
        </CardFooter>
      </Card>
    </div>
  );
}
